### ISSUE TITLE
Does edu.gatech.i3l.fhir.dstu2.entities.Vocabulary work?

### ISSUE THREAD

**Issue by sptrakesh** [gt-health/GT-FHIR#106]
When trying to generate the DDL for Vocabulary, hibernate throws an error.  This is because the primary key field id is declared as String, but has a GeneratedValue annotation.

**Comment by myungchoi** [comment]
Vocabulary table in OMOP is read-only. We are not writing anything there. I thought we annotated it as read-only. But, since we are not writing anything, we should be fine.

**Comment by sptrakesh** [comment]
No issues, I changed the definition to at least get the database creation to go through to the end.

**Comment by myungchoi** [comment]
By the way, GT-FHIR is heavily depending on the OMOP CDM. And, using vocabulary and concept tables are very critical. So, you may want to get this database build-up first. Otherwise, you won't be able to read or write FHIR resources. Our OMOP CDM requires some licensing. So, we can't share this. But, you can get this from ODHSI directly. If you need help on getting this database set up, please let me know. I will see if we can build something that we can share.

**Comment by sptrakesh** [comment]
We do have a OMOP database created in another application.  I was trying to get this implementation to generate the tables so we can compare the two database schemas and see if your implementation can be adapted easily to a few additions we made to the OMOP CDM.
